### ISSUE TITLE
npm start problem

### ISSUE THREAD

**Issue by mkalyon** [herudi/electron-google-drive-video#1]
Hi, 
I get following error
Can you help me How can I solve it? Thanks
#npm install
...
....
....
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN electron-google-drive-video@1.0.0 license should be a valid SPDX license expression

added 158 packages in 13.07s
# npm start

> electron-google-drive-video@1.0.0 start /var/www/test/electron-google-drive-video
> electron .

/var/www/test/electron-google-drive-video/node_modules/electron/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-google-drive-video@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the electron-google-drive-video@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-05T12_10_28_691Z-debug.log

**Comment by herudi** [comment]
try this
update npm
npm cache clean

**Comment by mkalyon** [comment]
Thank you I have solved.
How can start in shell, I dont use graphic screen.
Now I get followin error.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-google-drive-video@1.0.0~prestart: electron-google-drive-video@1.0.0
6 info lifecycle electron-google-drive-video@1.0.0~start: electron-google-drive-video@1.0.0
7 verbose lifecycle electron-google-drive-video@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle electron-google-drive-video@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/test/electron-google-drive-video/node_modules/.bin:/usr/local/sbin:/usr/local/
bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle electron-google-drive-video@1.0.0~start: CWD: /var/www/test/electron-google-drive-video
10 silly lifecycle electron-google-drive-video@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle electron-google-drive-video@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle electron-google-drive-video@1.0.0~start: Failed to exec start script
13 verbose stack Error: electron-google-drive-video@1.0.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid electron-google-drive-video@1.0.0
15 verbose cwd /var/www/test/electron-google-drive-video
16 verbose Linux 3.16.0-4-amd64
17 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error electron-google-drive-video@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the electron-google-drive-video@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


Thanks.

**Comment by SimDonovan** [comment]
Not working, in php pls?

**Comment by varunchopra** [comment]
@mkalyon This uses electron. If you want to use the shell, use node specifically. 

@SimDonovan Post your error.

**Comment by if1mad** [comment]
I tried firing up a digitalocean droplet to test this out (had to increase RAM to install stuff properly) but running into issues getting it started, using ubuntu 16.04. Any help appreciated. :)

After installing lots of missing dependencies it is giving this error:
```
root@ubuntu-2gb-lon1-01:~/electron-google-drive-video# npm start

> electron-google-drive-video@1.0.0 start /root/electron-google-drive-video
> electron .


npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! electron-google-drive-video@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-google-drive-video@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-google-drive-video package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-google-drive-video
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-google-drive-video
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/electron-google-drive-video/npm-debug.log

```

Contents of the log:

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-google-drive-video@1.0.0~prestart: electron-google-drive-video@1.0.0
6 silly lifecycle electron-google-drive-video@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle electron-google-drive-video@1.0.0~start: electron-google-drive-video@1.0.0
8 verbose lifecycle electron-google-drive-video@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electron-google-drive-video@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/electron-google-drive-video/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/u$
10 verbose lifecycle electron-google-drive-video@1.0.0~start: CWD: /root/electron-google-drive-video
11 silly lifecycle electron-google-drive-video@1.0.0~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle electron-google-drive-video@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle electron-google-drive-video@1.0.0~start: Failed to exec start script
14 verbose stack Error: electron-google-drive-video@1.0.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electron-google-drive-video@1.0.0
16 verbose cwd /root/electron-google-drive-video
17 error Linux 4.4.0-87-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error electron-google-drive-video@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the electron-google-drive-video@1.0.0 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron-google-drive-video package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron-google-drive-video
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron-google-drive-video
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by varunchopra** [comment]
@Qwatuz this is an Electron app...

**Comment by herudi** [comment]
@Qwatuz Try this in your terminal
npm uninstall electron request string --save
rm -rf node_modules
npm install electron request string --save-dev
electron .

**Comment by tia3** [comment]
Hello, I've got a centos 6 with this errors
Could anyone help me how to fix this?

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
> 2 info using npm@5.3.0
> 3 info using node@v8.2.1
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle electron-google-drive-video@1.0.0~prestart: electron-google-drive-video@1.0.0
> 6 info lifecycle electron-google-drive-video@1.0.0~start: electron-google-drive-video@1.0.0
> 7 verbose lifecycle electron-google-drive-video@1.0.0~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle electron-google-drive-video@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/share/nginx/html/electron-google-$
> 9 verbose lifecycle electron-google-drive-video@1.0.0~start: CWD: /usr/share/nginx/html/electron-google-drive-video
> 10 silly lifecycle electron-google-drive-video@1.0.0~start: Args: [ '-c', 'electron .' ]
> 11 info lifecycle electron-google-drive-video@1.0.0~start: Failed to exec start script
> 12 verbose stack Error: electron-google-drive-video@1.0.0 start: `electron .`
> 12 verbose stack spawn ENOENT
> 12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
> 12 verbose stack     at emitTwo (events.js:125:13)
> 12 verbose stack     at ChildProcess.emit (events.js:213:7)
> 12 verbose stack     at maybeClose (internal/child_process.js:921:16)
> 12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 13 verbose pkgid electron-google-drive-video@1.0.0
> 14 verbose cwd /usr/share/nginx/html/electron-google-drive-video
> 15 verbose Linux 2.6.32-696.6.3.el6.x86_64
> 16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
> 17 verbose node v8.2.1
> 18 verbose npm  v5.3.0
> 19 error file sh
> 20 error code ELIFECYCLE
> 21 error errno ENOENT
> 22 error syscall spawn
> 23 error electron-google-drive-video@1.0.0 start: `electron .`
> 23 error spawn ENOENT
> 24 error Failed at the electron-google-drive-video@1.0.0 start script.
> 24 error This is probably not a problem with npm. There is likely additional logging output above.
> 25 verbose exit [ 1, true ]

thank you in advice
